server:
  port: 80
spring:
  application:
    name: cloud-consumer-order80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

ribbon:
  # 建立连接所用时间
  ReadTimeout: 5000
  # 建立连接后读取可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # 选择具体接口的方法 的日志输出 级别为debug
    com.wxh.springcloud.service.PaymentFeignService: debug